Floating Action Button Disappears when list of topic is scrolled. #117
mgolokhov/dodroid pull request #120
Opened 2019-10-21 11:49 UTC by djubreel

- This PR fixes the issue with FAB Disappearing.
- A listener was added to the hide method, it seems the hide method does some layout actions that remove the view.

2019-10-21 19:45 UTC, mgolokhov commented
@djubreel thank you for the pull request.
After minor fixes, it can be merged.
Please check the comments.

2019-10-21 19:53 UTC, mgolokhov requested changes

2019-10-21 19:53 UTC, mgolokhov commented on app/src/main/java/doit/study/droid/Utils/Sound.java
> +package doit.study.droid.Utils;
Please revert to the initial lower case.
Kotlin's naming conversions https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules

2019-10-21 19:53 UTC, mgolokhov commented on app/src/main/java/doit/study/droid/activities/DrawerBaseActivity.kt
> +import android.provider.MediaStore.getVersion
Wrong import, should be `import doit.study.droid.utils.Distribution.getVersion`

2019-10-21 19:53 UTC, mgolokhov commented on app/src/main/java/doit/study/droid/fragments/TopicsChooserFragment.kt
>          setHasOptionsMenu(true)
Revert file to the initial state, please.

2019-10-21 19:53 UTC, mgolokhov commented on app/src/main/java/doit/study/droid/views/ScrollAwareFABBehavior.kt
> +                }
You override nothing, `onShown()` can be removed.

2019-10-21 19:53 UTC, mgolokhov commented on app/src/main/res/layout/fragment_topics_chooser.xml
>  </androidx.coordinatorlayout.widget.CoordinatorLayout>
The file can be reverted to the initial state.

2019-10-22 09:14 UTC, djubreel commented
Gone through the comments and made adjustments.

2019-10-22 09:51 UTC, mgolokhov commented
@djubreel 
Just a final step to rename folder Utils -> utils

2019-10-22 13:50 UTC, djubreel commented
@mgolokhov I've done that, you can verify that via the import statements.

2019-10-22 14:06 UTC, qps-ua-mgolokhov commented
@djubreel https://github.com/djubreel/dodroid/tree/master/app/src/main/java/doit/study/droid
![Screenshot 2019-10-22 at 17 05 28](https://user-images.githubusercontent.com/39056765/67294207-33cd5800-f4ee-11e9-8315-2d8192d7503e.png)

2019-10-22 15:02 UTC, mgolokhov commented
@djubreel https://github.com/djubreel/dodroid/tree/master/app/src/main/java/doit/study/droid
![67294207-33cd5800-f4ee-11e9-8315-2d8192d7503e](https://user-images.githubusercontent.com/294512/67300032-0d131f80-f4f6-11e9-8443-f346a8364654.png)

2019-10-23 10:09 UTC, djubreel commented
I have no idea why. It's lowercased on my local.
Check your repo, it's the same there.

2019-10-23 18:22 UTC, merged